### PR TITLE
always show physical keyboard layout

### LINKED ISSUE #1: [Suggestion] Support for other keyboard layout

### PR DESCRIPTION
**Pull request by thecatcore**
I've tested it with my french physical keyboard, works well.
The only "issue" I've found so far also affect vanilla, is this doesn't support virtual keyboard layout at least on Linux.

Closes #1

### CODE REVIEW

**Comment by thecatcore** [comment]
this is how it looks like with my layout:
image

**Comment by Einjerjar** [comment]
Can I get more context on the "doesn't support virtual layout part"? I'm currently unable to comprehend the issue (possibly because I have never encountered it), could I perhaps have an image of the expected layout?

As far as I can see, it seems to mainly revolve around the fact that some text doesn't get capitalized (something I forgot to do on the export stage of the keymap-helper, sorry), in which case, what if we instead do a toUpperCase pass as soon as the layout is loaded and passed to the BasicKeyData class?

**Comment by thecatcore** [comment]
The context of the picture is that I took it while having the en_us layout of the mod. And my os/physical keyboard being french.

**Comment by thecatcore** [comment]
My change, makes the gui render keys as they are on the keyboard, like vanilla but uppercased, except for keys with long name that you set short name to.

**Comment by Einjerjar** [comment]
Ah, that makes sense, currently the mod relies on minecraft's current language to detect the layout, I did try to do some searching some time earlier to try and figure out the keyboard layout from the OS, but wasnt able to make it work properly so I just settle for the cheap way of basing it off the current language, which I suppose is definitely wrong.

Unfortunately, doing it this way (this pull request) will kinda beat the purpose of the layout selection, since it will override the display keys for all the layout, regardless of any setting (current language, and layout override)

Instead of this and the automatic detection method, I'm thinking of instead showing the user a menu to choose their keyboard layout when they view the keymapper for the first time, while still allowing the user to choose their layout via the modmenu settings, preferably an interactive one, and probably a button within the keymapper to quickly view the settings page.

any thoughts?

**Comment by Einjerjar** [comment]
Forgot to close this, you can now manually select the preferred layout via a button on the keybinding screen itself

**Pull request closed without merging**
