### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by douira**
This PR updates the current version of keymap to 1.19. The bulk of the changes is updating `Text`. It currently doesn't run because of the following error:
```
Could not execute entrypoint stage 'client' due to errors, provided by 'modmenu'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
EntrypointUtils.java:51
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
ExceptionUtil.java:33
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
EntrypointUtils.java:49
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
EntrypointUtils.java:35
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
Hooks.java:53
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:443)
MinecraftClient.java:443
	at net.minecraft.client.main.Main.main(Main.java:198)
Main.java:198
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
MinecraftGameProvider.java:461
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
Knot.java:74
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
KnotClient.java:23
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Main.java:86
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_316
	at com.terraformersmc.modmenu.config.ModMenuConfig.<clinit>(ModMenuConfig.java:19)
...
```
I don't know how to solve this but I thought it would at least be helpful to have updated it this far.

Additionally there is this mixin warning, I don't know if this is something one has to worry about or not:
```
ControlsOptionsScreenMixin.java:21: warning: Unable to determine descriptor for @Inject target method
    @Inject(at = @At("HEAD"), method = "method_19872", cancellable = true)
```
(You'll probably want to re-enable the extra mods included in the gradle config)

Thanks for creating such an amazing keymapping mod!

### CODE REVIEW

**Comment by douira** [comment]
I have added the additional performance mods now. There are more crashes on launch now, this might be an incompatibility or I just did something wrong. I'm interested in hearing from you.

**Comment by Einjerjar** [comment]
Hey there! thanks for the wonderful work, unfortunately, I've already started working on a rewrite of the mod _(under the [v2](https://github.com/Einjerjar/keymap/tree/v2) branch)_, and I am planning to drop the current master branch, that said, the rewrite should not only cover the previous versions (1.17.1, 1.18.2), but also 1.19.0, and also a forge port for the same versions, hopefully, I will be able to release something within this week.

Sorry for the inconvenience, I will update the master's README asap.

**Comment by douira** [comment]
Thanks for the reply. I made this PR to support 1.19 faster than the rewrite might take. I was under the impression that updating the current version would allow people to use keymap earlier on 1.19 while you are still working on the rewrite.

Making this PR was fairly trivial except for the aforementioned issue.

**Comment by Einjerjar** [comment]
I suppose that is true, in which case, ill see what I can do.

**Comment by Einjerjar** [comment]
oh, also, you can pretty much ignore the "_ControlsOptionsScreenMixin_" warning, that's just due to the fact that the code is tapping directly to an unmapped (_no loom mapping_) lambda.

**Comment by Einjerjar** [comment]
and it's up, https://www.curseforge.com/minecraft/mc-mods/keymap/files/3852965,

once again, thanks for the wonderful work! :D

**Comment by douira** [comment]
Thanks for the kind words, it means a lot! This is the first doing actual modding, usually I just work on external library (glsl-transformer).

For some reason it crashes when I try to launch it in my development environment (clone of this repo) with the error I posted in the first comment in this thread. Do you know what's up with that? It runs fine if I put the jar in my mods folder but not if I use my IDE's launch configuration.

**Comment by Einjerjar** [comment]
Same goes!, thanks for the contributions!

For the error tho, I'm not completely sure either, could you try checking if the dev env's ModMenu version matches the one you are using outside development? If it is, and the issue persists, then I am completely lost myself.

**Comment by douira** [comment]
Ok thanks I'll look into it!

**Comment by douira** [comment]
I have updated modmenu to the correct version `4.0.0` for 1.19 (version 3 is wrong for 1.19 and doesn't actually exist) so I'll probably make another PR.

I have also identified C2ME as the cause of the crashes in the dev environment: (and presumably also outside of the dev environment)

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'c2me'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
EntrypointUtils.java:51
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
ExceptionUtil.java:33
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
EntrypointUtils.java:49
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
EntrypointUtils.java:35
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
Hooks.java:52
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:443)
MinecraftClient.java:443
	at net.minecraft.client.main.Main.main(Main.java:198)
Main.java:198
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
MinecraftGameProvider.java:461
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
Knot.java:74
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
KnotClient.java:23
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Main.java:86
Caused by: java.lang.NoClassDefFoundError: com/ibm/asyncutil/util/Combinators
	at com.ishland.c2me.C2MEMod.consistencyTest(C2MEMod.java:90)
C2MEMod.java:90
	at com.ishland.c2me.C2MEMod.onInitialize(C2MEMod.java:44)
C2MEMod.java:44
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
EntrypointUtils.java:47
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.ibm.asyncutil.util.Combinators
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
BuiltinClassLoader.java:641
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
ClassLoader.java:520
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
KnotClassDelegate.java:226
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
KnotClassLoader.java:145
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
ClassLoader.java:520
	... 11 more
```

I have also heard that this 1.19 update of keymap crashes on Quilt (maybe only in combination with specific mods?). I don't know much about all of this... Good that you marked it as a beta on CF since it does seem to be slightly, but not fatally, broken.

**Comment by douira** [comment]
I have identified that C2ME is missing the dependency `com.ibm.async:asyncutil:0.1.0` in the dev environment. If I add it explicitly, it launches in the dev environment: https://github.com/douira/keymap/blob/1.19-explicit-c2me-dep/build.gradle
But I have no idea why this is necessary since I was under the impression that nested dependency of mods would be preserved when including them as `modRuntimeOnly`. Do you know more about this? I'm new to this whole system

**Comment by Einjerjar** [comment]
my bad, haven't checked back on this issue recently, unfortunately I myself am not so familiar with the working of gradle, but as you said, I'm pretty sure that should have been handled automatically

**Pull request merged**
